version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - "3306"
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - chatboom-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    expose:
      - "6379"
    volumes:
      - ./redis:/data
    networks:
      - chatboom-network

  javaMicro:
    image: ethst/sensitive:latest
    container_name: sensitive
    restart: always
    expose:
      - "8081"
    networks:
      - chatboom-network

  chatboom:
    image: ethst/chatboom:stable
    container_name: chatboom
    restart: always
    ports:
      - "8094:8094"
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DATABASE}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      SERVE_STATIC: "true"
    volumes:
      - ./config:/config
      - ./logs:/logs
      - ./storage:/storage
    networks:
      - chatboom-network

networks:
  chatboom-network:
    driver: bridge
