name: Deploy Application

on:
  workflow_run:
    workflows: [ "Docker Image CI" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH Keys
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Add SSH key to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy with Docker Compose
        run: |
          ssh -T ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd ${{ secrets.DOCKER_COMPOSE_PATH }}
            docker-compose pull
            docker-compose up -d
          EOF
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
