name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get date and hash
        id: prep
        run: |
          echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
          SHORT_SHA="$(echo $GITHUB_SHA | head -c 7)"
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "::set-output name=date::$(date +'%Y%m%d')"
          echo "::set-output name=sha::$SHORT_SHA"

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/chatboom:latest
            ${{ secrets.DOCKER_USERNAME }}/chatboom:${{ steps.prep.outputs.date }}-${{ steps.prep.outputs.sha }}
